server:
  port: 8080

#spring.application.name=KnowCatFUD

spring:
  application:
    name: KnowCatFUD

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

  datasource:
    username: root
    password: root
    # 可能需要设置时区
    url: jdbc:mysql://localhost:3306/knowcatfud?userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
     # password:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: admin
    password: 123456
logging:
  level:
    root: info
    life.trally.knowcatfud: debug
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} %level %logger{36} - %msg%n"
  file:
    name: logs/log.log
  logback:
    rollingpolicy:
      file-name-pattern: "logs/%d{yyyy-MM-dd-HH}-%i.log"
      max-file-size: 10MB
