server:
  port: 8080

#spring.application.name=KnowCatFUD

spring:
  application:
    name: KnowCatFUD

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  #  security:
#    user:
#      name: default
#      password: 123

  datasource:
    username: root
    password: root
    # 可能需要设置时区
    url: jdbc:mysql://localhost:3306/knowcatfud?userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
     # password:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
